### ISSUE TITLE
Unable to debug step by step.

### ISSUE THREAD

**Issue by slaff** [espressif/esp-gdbstub#3]
I am trying to incorporate esp-gdbstub into Sming (https://github.com/slaff/Sming/tree/feature/gdb-dev), an esp C++ framework. And I have some difficulties debugging step by step. It would be great if someone can tell me what am I doing wrong.

So I compiled the sample program ( https://github.com/slaff/Sming/blob/feature/gdb-dev/Basic_Debug/app/application.cpp ) that turns the led on and off. I flashed it on the device and restart the devices. Then started gdb with the following options

```bash
xt-gdb -b 115200
```   

When gdb started I ran the following commands
```
(gdb) file out/build/app.out 
(trace) gdbarch_init()
Load new symbol table from "/media/slavey/416431e8-fd46-4982-896d-5025a72dd361/slavey/dev/esp8266.dev.box/dev/Sming/Basic_Debug/out/build/app.out"? (y or n) y
(trace) gdbarch_init()
Reading symbols from /media/slavey/416431e8-fd46-4982-896d-5025a72dd361/slavey/dev/esp8266.dev.box/dev/Sming/Basic_Debug/out/build/app.out...done.
(gdb) set remotedebug 1
No symbol "remotedebug" in current context.
(gdb) set remotelogfile gdb_rsp_logfile.txt
(gdb) set serial baud 115200
Undefined set serial command: "baud 115200".  Try "help set serial".
(gdb) set remotebaud 115200
(gdb) set remote hardware-breakpoint-limit 1
(gdb) set remote hardware-watchpoint-limit 1
(gdb) set debug xtensa 4
(gdb) target remote /dev/ttyUSB0
Remote debugging using /dev/ttyUSB0
(trace) xtensa_unwind_pc (next_frame = 0x97f2120)
(info ) [xtensa_unwind_pc] pc = 0x40237c27
gdbstub_do_break_breakpoint_addr () at /home/slavey/dev/esp8266.dev.box/dev/Sming/Sming//gdbstub/gdbstub-entry.S:399
399		break 0,0

(gdb) break init
(trace) xtensa_alloc_frame_cache ()
(trace) call0_analyze_prologue (start = 0x40237c27, pc = 0x40237c27, ...)
(verb ) [call0_analyze_prologue] stopped at instr addr 0x40237c27, succeeded
(trace) xtensa_skip_prologue (start_pc = 0x40105678)
(trace) xtensa_skip_prologue (start_pc = 0x40105678)
(trace) xtensa_breakpoint_from_pc (pc = 0x40105678)
Breakpoint 1 at 0x40105678: file app/application.cpp, line 22.

(gdb) l
394		addi	a1, a1, -16
395		s32i	a15, a1, 12
396		mov		a15, a1
397	
398	gdbstub_do_break_breakpoint_addr:
399		break 0,0
400	
401		mov		a1, a15
402		l32i	a15, a1, 12
403		addi	a1, a1, 16
(gdb) run
The "remote" target does not support "run".  Try "help target" or "continue".
```
Up to here everything seems to be work as expected. The LED on the device is not blinking and I can start the program.

```
(gdb) continue
Continuing.
(trace) xtensa_breakpoint_from_pc (pc = 0x40105678)
(trace) xtensa_breakpoint_from_pc (pc = 0x40105678)
(trace) xtensa_unwind_pc (next_frame = 0x97f2120)
(info ) [xtensa_unwind_pc] pc = 0x40105678
```

The debugger stops at the first breakpoint, which is great.

```
Breakpoint 1, init () at app/application.cpp:22
22	{
```

I can also see information about variables

```
(gdb) print state
$1 = true
```

*But then I am not able to debug the application step by step*. On the first execution of "next" I get back some result but all following next commands give me errors ```
Cannot find bounds of current function```.

Below is an output with more results.

```
(gdb) next
(trace) xtensa_alloc_frame_cache ()
(trace) call0_analyze_prologue (start = 0x40105678, pc = 0x40105678, ...)
(verb ) [call0_analyze_prologue] stopped at instr addr 0x40105678, succeeded
(trace) xtensa_unwind_pc (next_frame = 0x97f2120)
(info ) [xtensa_unwind_pc] pc = 0x40000504
(trace) xtensa_alloc_frame_cache ()
(trace) xtensa_unwind_pc (next_frame = 0x97f2180)
(info ) [xtensa_unwind_pc] pc = 0x40235cef
(trace) xtensa_alloc_frame_cache ()
(trace) call0_analyze_prologue (start = 0x40235cc8, pc = 0x40235cef, ...)
(verb ) [call0_analyze_prologue] instr addr = 0x40235cc8, opc = 16
(trace) call0_classify_opcode (..., opc = 16)
(verb ) [call0_analyze_prologue] instr addr = 0x40235ccb, opc = 74
(trace) call0_classify_opcode (..., opc = 74)
(verb ) [call0_analyze_prologue] instr addr = 0x40235cce, opc = 53
(trace) call0_classify_opcode (..., opc = 53)
(verb ) [call0_analyze_prologue] stopped at instr addr 0x40235cce, succeeded
0x40000504 in ?? ()
(gdb) next
Cannot find bounds of current function
```

Can it be that I am typing the next command too slow ( I don't think it takes me more than a second to press enter ) ? Or is the location of the function not correct ? I have instructions saying that the ```init``` function should be in ```.iram.text``` section. Is that the right place? 

Any ideas why "next" is not working or what am I doing wrong?

P.S: If I remove the breakpoint and run continue then the LED starts to blink and I can see the usual output:

```
(gdb) delete 1
(gdb) continue
Continuing.
(trace) xtensa_alloc_frame_cache ()
(trace) call0_analyze_prologue (start = 0x40105678, pc = 0x40105678, ...)
(verb ) [call0_analyze_prologue] stopped at instr addr 0x40105678, succeeded
mode : softAP(1a:fe:34:f3:74:e7)
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
```

**Comment by Spritetm** [comment]
This is a known issue (that unfortunately you are the first one to properly report on Github... gotta remember to create an issue myself if I get them mailed): basically, an interrupt can 'hijack' the single step, making it look like the CPU did nothing while actually it executed the interrupt routine instead of the instruction. Fix coming up, I should finally have some time for that this week.

**Comment by Spritetm** [comment]
Also, I see you use xt-gdb, which is probably the Tensilica-built GDB. This stub is made to work with the open-source xtensa-lx106-elf-gdb as built by e.g. xtensa-open-sdk.

**Comment by slaff** [comment]
@Spritetm 
> Also, I see you use xt-gdb, which is probably the Tensilica-built GDB.
I am using the esp-open-sdk. The xt-gdb is just a link to the xtensa-lx106-elf-gdb. 

Thanks in advance for your efforts. Debugging will help us greatly figure out strange issues with the devices and our C/C++ code.

**Comment by Spritetm** [comment]
Okay, please check out commit 7c9e0ca and see if you can reproduce the problem?

**Comment by slaff** [comment]
@Spritetm Works like charm! Thanks a lot. Take a look here: 
![Live debugging session in Eclipse](https://pbs.twimg.com/media/CVFpXf8WsAATeHW.png:large)

I have one question though - in the README you say that breakpoints can be set only to code which resides in RAM. If a function, that was located in FLASH, is executed then is its code moved to RAM  after its first execution?  If yes, can I set a breakpoint somewhere inside of it after the first execution? I am asking because I can debug deeper than I was expecting and set breakpoints to functions that were not explicitly declared to reside in RAM and I am, happy of course, but would like to know why is that possible?

**Comment by Spritetm** [comment]
I actually think gdb reverts to single-stepping every single instruction if it detects it can't set a software breakpoint at a certain position, or it may revert to ha hardware breakpoint if it still is unused.
