### ISSUE TITLE
XCHAL_DEBUGLEVEL

### ISSUE THREAD

**Issue by berkutta** [espressif/esp-gdbstub#7]
It couldn't find XCHAL_DEBUGLEVEL in my constelation with the standard IoT SDK.

**Comment by Spritetm** [comment]
What compiler toolchain do you use? (You should have a core-isa.h file somewhere there that defines it.)

**Comment by berkutta** [comment]
Seems to be a Issue from me. Now it compiles without any flaw. I now only have the Issue that the GDB can't connect to it. On the web everyone says 115200 is the correct baudrate for gdb, but the sysprogs environment uses 74880. What is now correct? Can I change it?

**Comment by Spritetm** [comment]
Okay, then I'll close this issue. The baud rate is not affected by gdbstub, it is whatever is set by your program. If you do printfs in your program and can see that data, that's the baud rate gdbstub will communicate on.
